"""
data_pipeline/provenance.py
-----------------------------
Provenance record creation and serialization for the pipeline.
SIH 2026 · PS 26059

Every dataset entering the scientific pipeline must carry a DataProvenance
record. This module provides helpers to create, update, and serialize them.

The serialized records are the backend contract for the Data Provenance UI
panel (Phase 5). They will be consumed by the frontend in Phase 7.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from .schemas import DataProvenance, DataQuality, DataSource

logger = logging.getLogger(__name__)


def create_provenance(
    source: DataSource,
    dataset_name: str,
    valid_time_start: datetime,
    valid_time_end: datetime,
    spatial_coverage: str,
    units: str,
    coordinate_system: str = "WGS84",
    status: DataQuality = DataQuality.AVAILABLE,
    notes: str = "",
    retrieved_at: Optional[datetime] = None,
) -> DataProvenance:
    """
    Create a DataProvenance record with retrieved_at defaulting to now (UTC).
    All datetimes must be UTC-aware.
    """
    if retrieved_at is None:
        retrieved_at = datetime.now(tz=timezone.utc)

    for name, dt in [
        ("retrieved_at", retrieved_at),
        ("valid_time_start", valid_time_start),
        ("valid_time_end", valid_time_end),
    ]:
        if dt.tzinfo is None:
            raise ValueError(f"{name} must be timezone-aware (UTC). Got naive datetime.")

    prov = DataProvenance(
        source=source,
        dataset_name=dataset_name,
        retrieved_at=retrieved_at,
        valid_time_start=valid_time_start,
        valid_time_end=valid_time_end,
        spatial_coverage=spatial_coverage,
        units=units,
        coordinate_system=coordinate_system,
        status=status,
        notes=notes,
    )
    logger.debug(
        "Created provenance: source=%s dataset=%s status=%s",
        source.value, dataset_name, status.value)
    return prov


def provenance_to_dict(prov: DataProvenance) -> Dict[str, Any]:
    """
    Serialize a DataProvenance to a JSON-compatible dict.
    This is the data contract for the frontend Provenance UI panel.
    """
    return {
        "source": prov.source.value,
        "dataset_name": prov.dataset_name,
        "retrieved_at": prov.retrieved_at.isoformat(),
        "valid_time_start": prov.valid_time_start.isoformat(),
        "valid_time_end": prov.valid_time_end.isoformat(),
        "spatial_coverage": prov.spatial_coverage,
        "units": prov.units,
        "coordinate_system": prov.coordinate_system,
        "status": prov.status.value,
        "notes": prov.notes,
    }


def provenance_to_json(prov: DataProvenance, indent: int = 2) -> str:
    """Serialize a DataProvenance to a JSON string."""
    return json.dumps(provenance_to_dict(prov), indent=indent)


def create_synthetic_provenance(
    dataset_name: str,
    valid_time_start: datetime,
    valid_time_end: datetime,
) -> DataProvenance:
    """
    Convenience factory for synthetic / demo data provenance records.
    Ensures demo data is never confused with real observations.
    """
    return create_provenance(
        source=DataSource.SYNTHETIC,
        dataset_name=f"[SYNTHETIC DEMO] {dataset_name}",
        valid_time_start=valid_time_start,
        valid_time_end=valid_time_end,
        spatial_coverage="Synthetic domain — not a real geographic region",
        units="varies (see dataset documentation)",
        status=DataQuality.AVAILABLE,
        notes=(
            "SYNTHETIC DATA ONLY. This record was generated by a deterministic "
            "fixture for SIH 2026 prototype demonstration. It does NOT represent "
            "real environmental conditions."
        ),
    )


def create_fixture_provenance(
    original_source: DataSource,
    dataset_name: str,
    valid_time_start: datetime,
    valid_time_end: datetime,
    spatial_coverage: str,
    units: str,
    notes: str = "",
) -> DataProvenance:
    """
    Provenance for a recorded real-data fixture (replay dataset).
    Distinguishes replayed real data from truly synthetic data.
    """
    return create_provenance(
        source=DataSource.FIXTURE,
        dataset_name=f"[FIXTURE] {dataset_name} (originally: {original_source.value})",
        valid_time_start=valid_time_start,
        valid_time_end=valid_time_end,
        spatial_coverage=spatial_coverage,
        units=units,
        status=DataQuality.AVAILABLE,
        notes=(
            f"Recorded replay of {original_source.value} data for deterministic testing. "
            + notes
        ),
    )
